# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a5af61256d0103af1f85cab458d568896fe5c69bcb7605ea6e5c1d97872fc17462b17dc3f6f8df5a1ac99d21b2b53648d3a8f3f4a19b3fc23c3e73e7abbee67

test:
  secret_key_base: eaea818e9f5fc67e66de428abb92d5fd70cd2fdab276fd74acb15754b519d673159e977a283d45ffa45a1f69eb92062cf8a7de842471a6e7283eda2215e9ca53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
